struct vm_area_struct {
	unsigned long vm_start; /* Начало области памяти */
	unsigned long vm_end; /* Конец области памяти */

	struct vm_area_struct *vm_next, *vm_prev; /* Следующая и предыдущая область памяти */
	...
	struct mm_struct *vm_mm; /* Адресное пространство, к которому принадлежит области памяти */
	...
	unsigned long vm_flags;
	...
	struct anon_vma *anon_vma; /* Описание анонимного отображения */
	...
	struct file *vm_file; /* Отображенный файл */
	...
}
